-- MySQL Script generated by MySQL Workbench
-- Пт 26 авг 2016 18:21:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dnsperfdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dnsperfdb` ;

-- -----------------------------------------------------
-- Schema dnsperfdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dnsperfdb` DEFAULT CHARACTER SET utf8 ;
USE `dnsperfdb` ;

-- -----------------------------------------------------
-- Table `dnsperfdb`.`domains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dnsperfdb`.`domains` ;

CREATE TABLE IF NOT EXISTS `dnsperfdb`.`domains` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` CHAR(255) NULL DEFAULT NULL,
  `average_query_time` DOUBLE NULL DEFAULT 0,
  `query_time_deviation` DOUBLE NULL DEFAULT 0,
  `query_count` INT NULL DEFAULT 0,
  `first_query_timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `final_query_timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dnsperfdb`.`queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dnsperfdb`.`queries` ;

CREATE TABLE IF NOT EXISTS `dnsperfdb`.`queries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latency` INT NULL DEFAULT 0,
  `domain_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_queries_domains_idx` (`domain_id` ASC),
  CONSTRAINT `fk_queries_domains`
    FOREIGN KEY (`domain_id`)
    REFERENCES `dnsperfdb`.`domains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `domains` (`url`) VALUE ('google.com');
INSERT INTO `domains` (`url`) VALUE ('facebook.com');
INSERT INTO `domains` (`url`) VALUE ('youtube.com');
INSERT INTO `domains` (`url`) VALUE ('yahoo.com');
INSERT INTO `domains` (`url`) VALUE ('live.com');
INSERT INTO `domains` (`url`) VALUE ('wikipedia.org');
INSERT INTO `domains` (`url`) VALUE ('baidu.com');
INSERT INTO `domains` (`url`) VALUE ('blogger.com');
INSERT INTO `domains` (`url`) VALUE ('msn.com');
INSERT INTO `domains` (`url`) VALUE ('qq.com');
